// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// i2c_master //
// ---------- //

#define i2c_master_wrap_target 0
#define i2c_master_wrap 30
#define i2c_master_pio_version 0

static const uint16_t i2c_master_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 0
    0x7041, //  1: out    y, 1            side 0
    0x7021, //  2: out    x, 1            side 0
    0x1066, //  3: jmp    !y, 6           side 0
    0xf881, //  4: set    pindirs, 1      side 1
    0xf180, //  5: set    pindirs, 0      side 0 [1]
    0x1031, //  6: jmp    !x, 17          side 0
    0x7081, //  7: out    pindirs, 1      side 0
    0xf027, //  8: set    x, 7            side 0
    0xb942, //  9: nop                    side 1 [1]
    0x5801, // 10: in     pins, 1         side 1
    0xb742, // 11: nop                    side 0 [7]
    0x1049, // 12: jmp    x--, 9          side 0
    0xf081, // 13: set    pindirs, 1      side 0
    0xb942, // 14: nop                    side 1 [1]
    0xf180, // 15: set    pindirs, 0      side 0 [1]
    0x1019, // 16: jmp    25              side 0
    0xf027, // 17: set    x, 7            side 0
    0x7181, // 18: out    pindirs, 1      side 0 [1]
    0xb942, // 19: nop                    side 1 [1]
    0xb742, // 20: nop                    side 0 [7]
    0x1052, // 21: jmp    x--, 18         side 0
    0x7181, // 22: out    pindirs, 1      side 0 [1]
    0xb942, // 23: nop                    side 1 [1]
    0xb742, // 24: nop                    side 0 [7]
    0x7041, // 25: out    y, 1            side 0
    0x107e, // 26: jmp    !y, 30          side 0
    0xf181, // 27: set    pindirs, 1      side 0 [1]
    0xb942, // 28: nop                    side 1 [1]
    0xf980, // 29: set    pindirs, 0      side 1 [1]
    0xb742, // 30: nop                    side 0 [7]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2c_master_program = {
    .instructions = i2c_master_program_instructions,
    .length = 31,
    .origin = -1,
    .pio_version = i2c_master_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2c_master_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2c_master_wrap_target, offset + i2c_master_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
static inline void i2c_master_program_init(PIO pio, uint sm, uint offset,
                                            uint pin_sda, uint pin_scl,
                                            uint32_t freq) {
    pio_sm_config c = i2c_master_program_get_default_config(offset);
    sm_config_set_out_pins(&c, pin_sda, 1);
    sm_config_set_set_pins(&c, pin_sda, 1);
    sm_config_set_in_pins(&c, pin_sda);
    sm_config_set_sideset_pins(&c, pin_scl);
    sm_config_set_in_shift(&c, false, true, 8);
    float div = (float)clock_get_hz(clk_sys) / ((float)freq * 13.0f);
    sm_config_set_clkdiv(&c, div);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_pindirs_with_mask(pio, sm,
        (1u << pin_scl),
        (1u << pin_sda) | (1u << pin_scl));
    gpio_pull_up(pin_sda);
}

#endif

